### ISSUE TITLE
ควรทำ sandbox หรือจำกัดการใช้งานด้วย

### ISSUE THREAD

**Issue by ouoam** [eXitHere/grader#6]
เนื่องจากตัว grader เปิดให้ใครเอาโค้ดอะไรก็ได้มารัน ซึ่งจะไม่รู้หลอกว่า โค้ดที่เอามารันนั้นทำมาเพื่อแก้โจทย์จริงๆ หรือโจมตีตัวระบบรึป่าว ซึ่งไม่ว่าจะเป็น การสั่งคำสั่งปิดเครื่อง สั่งคำสั่งปิดโปรแกรมอื่นๆ แก้ไขไฟล์ ใช้เน็ตเวิร์คไปโจมตีคนอื่น หรือไปทำอะไรทุ่มมุ้งร้ายอื่นๆ ที่อาจส่งผลกระทบต่อระบบของเรา หรือของคนอื่น ให้เกิดความเสียหายได้ ล้วนเป็นสิ่งที่ควรจะป้องกันไม่ให้เกิดขึ้นกับระบบของเราทั้งสิ้น

จึงเสนอวิธีการแก้ปัญหาด้วยวิธีต่างๆดังนี้
- ลบ header file ตัวที่ไม่จำเป็นต้องใช้ออกไป (programming.in.th ตัวเก่าใช้วิธีนี้)
- สร้าง sandbox จำกัดการใช้งานโปรแกรม (grader ioi 2007 ถึงล่าสุด ใช้วิธีนี้ และส่วนใหญ่ก็เลือกใช้)
- สร้าง docker แยก (ถ้าทำแยกของทุกโปรแกรม หรือของทุกคน มันก็เปลืองทรัพยากร)
- สร้าง vm แยก (มันเปลืองทรัพยากรมากมาก)

สำหรับ sandbox สามารถใช้ตัวนี้ได้ [isolate](https://github.com/ioi/isolate) เป็นของ ioi ที่เอาไว้ใช้กับ grader ของ ioi มาตั้งแต่ปี 2012 (ไม่เคยลองเล่นเหมือนกัน)

หรือจะใช้ระบบที่มีตอนสร้างไว้สำหรับเป็นตัว compile แล้วก็รันโค้ด [judge0](https://github.com/judge0/api) ซึ่งใช้งานด้วย json rest api ซึ่งรองรับการ compile และ/หรือ run ได้หลากหลายภาษา สามารถใส่ input และตรวจ output ให้เราได้เลย มีระบบจำกัดเวลา จำกัดการใช้เมมโมรี่ และก็มีระบบ sandbox ด้วย (ใช้ในระบบของปีที่แล้ว และปีที่แล้วของปีที่แล้ว)

หรือถ้าคิดว่าน้องปีนี้จะเป็นเด็กดี ไม่ซนอะไร ก็ไม่ต้องทำก็ได้

ปล. มีเพื่อนพี่ถามว่าทำไมไม่ใช้ deno อีกละ มันก็สามารถใช้ exec ได้เหมือนกันนะ

**Comment by eXitHere** [comment]
ขอบคุณสำหรับคำแนะนำครับ ตอนนี้กำลังแก้โดยการลบ Lib ออกจากตัว compiler อยู่ครับ
